apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipcoin
  labels:
    app: flipcoin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flipcoin
  template:
    metadata:
      labels:
        app: flipcoin
    spec:
      containers:
        - name: flipcoin
          image: 307987836148.dkr.ecr.us-east-1.amazonaws.com/dev-app:60bdefe
          ports:
            - containerPort: 3000
