apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: next-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RESTfulAyush/gitops-environments.git
    targetRevision: HEAD
    path: dev/flipcoin
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
